<?php
$response = array();
$response['valid'] = false;
$response['msg'] = '';

$objects = [
	"Articles"	=> [
		["url" => "article.php", "image" => "ingwersen.jpg", "height" => "200", "background-size" => "cover", "subtopic" => "Bibliometric", "title" => "The Calculation of Web Impact Factors", "reference" => "Ingwersen, P. Journal of Documentation, 1998. agade: 2016.039204.1", "views" => "14", "citations" => "32", "indicators" => ["green", "green", "orange", "green"], "abstract" => "This case study reports the investigations into the feasibility and reliability of calculating impact factors for web sites, called Web Impact Factors (Web‐IF). The study analyses a selection of seven small and medium scale national and four large web domains as well as six institutional web sites over a series of snapshots taken of the web during a month. The data isolation..."],
		["url" => "article.php", "image" => "vannevar.jpg", "height" => "200", "background-size" => "auto 200px", "subtopic" => "Information Science", "title" => "As We May Think", "reference" => "Vannevar, B. The Atlantic, 1945. agade: 2016.039203.1", "views" => "14", "citations" => "32", "indicators" => ["green", "orange", "gray", "green"], "abstract" => "This has not been a scientist's war; it has been a war in which all have had a part.  The scientists, burying their old professional competition in the demand of a common cause, have shared greatly and learned much.  It has been exhilarating to work in effective partnership.  Now, for many, this appears to be approaching an end. What are the scientists to do next?"],
		["url" => "article.php", "image" => "verdu.jpg", "height" => "200", "background-size" => "cover", "subtopic" => "Information Theory", "title" => "Fifty Years of Shannon theory", "reference" => "Verdu, S. IEEE Transactions on Information Theory, 1998. agade: 2016.039203.1", "views" => "14", "citations" => "32", "indicators" => ["green", "green", "orange", "green"], "abstract" => "A brief chronicle is given of the historical development of the central problems in the theory of fundamental limits of data compression and reliable communication."],
		["url" => "article.php", "image" => "", "height" => "0", "background-size" => "", "subtopic" => "Bibliometric", "title" => "The Calculation of Web Impact Factors", "reference" => "Ingwersen, P. Journal of Documentation, 1998. agade: 2016.039204.1", "views" => "14", "citations" => "32", "indicators" => ["green", "green", "orange", "green"], "abstract" => "This case study reports the investigations into the feasibility and reliability of calculating impact factors for web sites, called Web Impact Factors (Web‐IF). The study analyses a selection of seven small and medium scale national and four large web domains as well as six institutional web sites over a series of snapshots taken of the web during a month. The data isolation and calculation methods are described and the tests discussed. The results thus far demonstrate that Web‐IFs are calculable with high confidence for national and sector domains whilst institutional Web‐IFs should be approached with caution. The data isolation method makes use of sets of inverted but logically identical..."],
		["url" => "article.php", "image" => "it.png", "height" => "290", "background-size" => "auto 280px", "subtopic" => "Information Theory", "title" => "Fifty Years of Shannon theory", "reference" => "Verdu, S. IEEE Transactions on Information Theory, 1998. agade: 2016.039203.1", "views" => "14", "citations" => "32", "indicators" => ["green", "orange", "green", "green"], "abstract" => "A brief chronicle is given of the historical development of the central problems in the theory of fundamental limits of data compression and reliable communication."],
		["url" => "article.php", "image" => "rissanen.jpg", "height" => "200", "background-size" => "cover", "subtopic" => "Information Theory", "title" => "Universal Modelling and Coding", "reference" => "Rissanen, J. and Langdon, G. IEEE Transactions on Information Theory, 1981. agade: 2016.039202.1", "views" => "14", "citations" => "32", "indicators" => ["green", "green", "orange", "green"], "abstract" => "The problems arising in the modeling and coding of strings for compression purposes are discussed. The notion of an information source that simplifies and sharpens the traditional one is axiomatized, and adaptive and nonadaptive models are defined. With a measure of complexity assigned to the models, a fundamental theorem is proved which states that models that use any kind of alphabet extension are inferior to the best models using no alphabet extensions at all. A general class of so-called first-in first-out (FIFO) arithmetic codes is described..."],
	],
	"Products"	=> [
		["url" => "product.php", "image" => "tv2.png", "height" => "208", "background-size" => "calc(100% - 9px) auto", "subtopic" => "Television", "title" => "Samsung UN55JU6500FXZA", "reference" => "January 2015. agade: 2016.039204.1", "views" => "14", "citations" => "32", "indicators" => ["green", "green", "orange", "green"], "abstract" => "With 4K UHD resolution you’ll enjoy a picture with 4X the detail of Full HD. Watch and play your way with the advanced Samsung Smart TV platform that lets you quickly and easily access your favorite content. Plus, this 4K UHD TV complies with the Consumer Electronics Association specification guideline requirements that includes full RGB color resolution."],
	],
	"Philately"	=> [
		["url" => "stamps.php", "image" => "stamp2.png", "height" => "135", "background-size" => "calc(100% - 9px) auto", "subtopic" => "Commemorative stamp", "title" => "190 Years of the Brazilian National Library", "reference" => "January 2000. agade: 2016.039204.1", "views" => "14", "citations" => "32", "indicators" => ["green", "green", "orange", "green"], "abstract" => "A Biblioteca Nacional (BN) é o órgão responsável pela execução da política governamental de captação, guarda, preservação e difusão da produção intelectual do País. Com mais de 200 anos de história, é a mais antiga instituição cultural brasileira.		Possui um acervo de aproximadamente 9 milhões de itens e, por isso, foi considerada pela UNESCO (Organização das Nações Unidas para a Educação, a Ciência e a Cultura) como uma das principais bibliotecas nacionais do mundo. Para garantir a manutenção desse imenso conjunto de obras, a BN possui laboratórios de restauração e conservação de papel, oficina de encadernação, centro de microfilmagem, fotografia e digitalização.		O acervo da BN cresce constantemente a partir da lei do depósito legal – que assegura o registro e a guarda da produção intelectual nacional, além de possibilitar o controle, a elaboração e a divulgação da Bibliografia Brasileira corrente, bem como a defesa e a preservação da língua e da cultura nacionais – além de doações e aquisições."],
	],
];
 
$response['objects'] = $objects;
echo json_encode($response, JSON_NUMERIC_CHECK);
?>